name: allure-report
on:
  push:
    branches: [dev]

jobs:
    generate-report:
        runs-on: ubuntu-latest
        environment: secrets
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'
            - run: |
                 npm i cypress
                 echo ${{secrets.MAIL_USERNAME}}
            
         
            - name: clear allure results
              run: npm run allure:clear
              
            - name: Run Cypress
              run: npm run cy:run
              
              
            - uses: actions/checkout@v2
            - name: Get Allure history
              uses: actions/checkout@v2
              if: always()
              continue-on-error: true
              with:
                ref: gh-pages
                path: gh-pages

            - name: Allure Report action from marketplace
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                allure_results: allure-results
                allure_history: allure-history
                keep_reports: 5

            - name: Deploy report page
              uses: peaceiris/actions-gh-pages@v3
              if: always()
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: ./
                user_name: "github-actions[bot]"
                user_email: "github-actions[bot]@users.noreply.github.com"
            
    deploy:
      needs: generate-report
      name: deploy
      if: ${{ always() }}
      runs-on: ubuntu-latest
      steps:
        - name: checkout branch report
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: example2


        - uses: actions/checkout@v2
        - uses: EdricChan03/action-build-deploy-ghpages@v3.1.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: example2


    sendmail:
        needs: deploy
        name: send mail

        if: ${{ always() }}
        runs-on: ubuntu-latest
        environment: secrets
        steps:
        - name: checkout branch report
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: dev
              
        - name: log 
          run: |
            git branch
            pwd

        - name: Send mail
          if: always()
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Report Message
            to: ${{secrets.LIST_MAILS}}
            from: ${{secrets.MAIL_USERNAME}}
            convert_markdown: true
            html_body: file://README.md